Finished PS11. But I couldn't get the pylab functions to work. They all hung with errors like:
NameError: global name 'plot' is not defined

I tried reinstalling matlab and all the required software, but I couldn't get it to work.